# Generated by Django 3.2 on 2023-08-24 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='В названии рецепта совсем нет букв', regex='.*[a-яA-ЯЁё].*')], verbose_name='Название блюда'),
        ),
    ]
