version: '3.3'
# name: fg
services:
  # db:
  #   image: postgres:13.0-alpine
      # volumes:
      #   -/var/lib/postgresql/data/
      # environment:
        # POSTGRES_DB: "db"
        # POSTGRES_HOST_AUTH_METHOD: 'trust'


  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  # backend:
#   build:
    # context: ../backend/foodgram
    # dockerfile: Dockerfile
#   restart: always
#   ports:
#     - "8000:8000"
#     - '3000:3000'
#   depends_on:
#     - db

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    #   - ../backend/foodgram/static:/var/html/static_backend/
    #   - media_value:/var/html/media
    #   - logs_value:/var/logs/
    # depends_on:
    #   - frontend
    #   -backend
# volumes:
#   static_backend_value:
#   frontend_value:
#   media_value:
#   logs_value:


