# Generated by Django 3.2 on 2023-08-08 18:06

import django.db.models.expressions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230808_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': (django.db.models.expressions.F('author__username'),), 'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
